language: Android
android:
	components:
		- build-tools-25.0.2
		- android-25
script:
    - ./gradlew build connectedCheck
    
skip_cleanup: true
deploy:
  provider: releases
  file: "CalculatorApp/build/outputs/apk/app-release.apk"
  on:
    repo: Deepankar-promact/CalculatorApp

   