language: android
jdk: oraclejdk8
android:
    components:
        - tools
        - build-tools-24.0.3
        - android-25
        - extra-android-support
script:
    - ./gradlew build connectedCheck

before_install:
    - chmod +x ./gradlew
    
skip_cleanup: true
   