language: android
jdk: oraclejdk8
android:
    components:
        - tools
        - build-tools-19
        - android-19
        - extra-android-support
script:
    - ./gradlew build connectedCheck

before_install:
    - chmod +x ./gradlew
    
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
skip_cleanup: true
   