language: android
jdk: oraclejdk8
    
env:
  global:
    - ANDROID_TOOLS_URL="https://dl.google.com/android/repository/tools_r25.0.2-linux.zip"
    
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - android-25
    - extra-android-support
    
  licenses:
    - android-sdk-preview-license-+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install: 
  - "chmod +x gradlew"