language: android
android:
  components:
  - tools
  - build-tools-24.0.1
  - android-24
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
jdk:
- oraclejdk8

script:
- "./gradlew build"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: LEb6GhE+cfjenyB21bNkf9AbkTWspHOVKc/tIf0ap2AM8VZKqMifhLBcnCCyjiaTAbKtUfBNx18HvpE4tT5Rer5TCuq2h1zWBlpjA2hLQeto76+fgra77sZ2CQlaVu891tbLMeHUHpGpotMrN+ASqPTQZkOjP9eitIuxKL1JQGOHUm1lC129Tz+/OO7GJHOrrj/AcQU6LicqHpbQ8mxLqDzfbqSB+Hk73KS4XVXLQ0X46xT5B+2Rpe1fM2/BSVJZ6C6qNiO8mr3I1dy9h74mzfl/fGv+OYPrzRkblwffJp7aNM7Qgm70/sS+SSMpee2+K/CzNiUcoNUPlrv00a5TXqoFox2yfCUkH9gtl3GHCcJHh9/ql5MVLhhQ0k9YymNGGCMyM+j8R6CDj31RXveaImq98/EnWZAA4xj3DYnJ4iYcL6uVIErIfiCytVwZjGg0Z8fSoNFMtqXbT3p04N9B4KNwPzgn6jEqGAMovRDAhuHxOnPRtJBYhFgrzsIqbIIstefKRjPuZ9KThMy7elA3hwdASvjl/h3mFKRDYscH6eM7kPM/2HEN0vIkoA1QT6GiwHs4u9wKqbBDpSzonicjEjBuvOMCWeLCQIt9GBSs/+7HcQ0iq1wUe+pP0gBvLQPPvGjiYdGPMq2uwUP3DDEMYkin+mWsntYkyocO00L5Bp0=
  file: 
    - "\app\build\outputs\apk\*.apk"
  on:
    repo: Deepankar-promact/CalculatorApp
