language: android
android:
    components:
        - build-tools-25.0.2
        - android-25
script:
    - ./gradlew build connectedCheck

before_install:
- chmod +x gradlew
    
skip_cleanup: true
   